### PR TITLE
Removed legacy code for tidalapi < 0.7 support

### PR DESCRIPTION
**Pull request by BlackLight**
Closes: #78

### CODE REVIEW

**Comment by BlackLight** [comment]
@2e0byo it looks like a few tests need to be changed - there are several failures due to the fact that we are now transparently passing `Mock` objects around instead of unpacking their values.

**Comment by 2e0byo** [comment]
@BlackLight I don't know how to pr against a pr...

These errors were all just the test suite assuming the old api as default (which worked since the mocked session didn't have the attributes whcih marked it as the new api).

All fixed and passing in https://github.com/2e0byo/mopidy-tidal/tree/remove-tidalapi-0-6-logic

Can you manually pull in that commit (or convert it to a patch and apply or something)?  Otherwise I can pr from my branch and we can merge that: the PR will show up as mine but the commits as yours, since I just forked from you.

**Comment by 2e0byo** [comment]
Actually it occurs to me that @tehkillerbee is likely not as silly as I am about only merging green commits.  In which case the simplest would be to merge this PR first, and then mine, repairing the test suite.  I'll open a pr.  But if @BlackLight modifies this PR I'll close mine.

**Review by tehkillerbee — APPROVED** [review]
LGTM

**Pull request merged**
