### PR TITLE
Always add newly created playlists to cache

### PR DESCRIPTION
**Pull request by BlackLight**
If `playlist_cache_refresh_secs` is unset then the playlist won't be automatically added to `_current_tidal_playlists`. We should do it explicitly if we want the backend to be able to immediately get its contents.

### CODE REVIEW

**Comment by tehkillerbee** [comment]
@BlackLight @2e0byo This PR fails all tests; do we need to update the tests as well?

**Comment by 2e0byo** [comment]
@tehkillerbee I'll get on this shortly.

**Comment by 2e0byo** [comment]
I think there was actually a bug in this PR.  We want to add the tidal playlist, not the mopidy playlist, to `_current_tidal_playlists`. So I think the test suite actually earned its keep.

However once this is fixed we need to fix the test suite, as `create()` now triggers a `refresh()`, so we have to mock `playlist.tracks` (to return nothing, and have a `__name__`).

The attached patch fixes this.
[0001-fix-cache-tidal-playlist-not-mopidy-playlist.txt](https://github.com/tehkillerbee/mopidy-tidal/files/11192220/0001-fix-cache-tidal-playlist-not-mopidy-playlist.txt)

**Comment by BlackLight** [comment]
Thanks for the fix @2e0byo!

**Review by tehkillerbee — APPROVED** [review]

**Pull request merged**
