### PR TITLE
v0.3.0 OAuth Flow Authentication

### PR DESCRIPTION
**Pull request by quodrum-glas**

### CODE REVIEW

**Comment by tehkillerbee** [comment]
@quodrum-glas I see you have made many new additions to the code, thanks for that. I notice that you have changed away from the tidalapi. May I ask why?

**Comment by tehkillerbee** [comment]
I just tested it with latest mopidy. I obtained my own token according to this guide: https://gist.github.com/artworked/3003fa0183b464a0b0d2ca2e77afe477 and configured the mopidy.conf accordingly. However, when trying to search for songs, following error occurs:

Dec 11 15:17:38 rpimedia systemd[1]: Starting Mopidy music server...
Dec 11 15:17:38 rpimedia systemd[1]: Started Mopidy music server.
Dec 11 15:17:39 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Dec 11 15:17:39 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Dec 11 15:17:39 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Dec 11 15:17:39 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Dec 11 15:17:39 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.config Loading config from command line options
Dec 11 15:17:40 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.__main__ Enabled extensions: softwaremixer, alsamixer, mpd, mobile, musicbox_webclient, m3u, tidal, file, http, stream
Dec 11 15:17:40 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: TidalBackend, FileBackend, M3UBackend, StreamBackend
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.backend Connecting to TIDAL.. Quality = HIGH
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink device=hw:1,0"
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:0.0.0.0]:6600
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [HttpFrontend-10] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Dec 11 15:17:41 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Dec 11 15:17:45 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.lru_cache Search cache miss
Dec 11 15:17:45 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.search Searching Tidal for:  {'any': ['Ben Lukas boysen']}
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-11] mopidy_tidal.utils Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:17:45 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:17:45 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:17:45 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:17:45 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 65, in run
Dec 11 15:17:45 rpimedia mopidy[5420]:     artists = self.session.search("artist", self.keyword).artists
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:17:45 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:17:45 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:17:45 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:17:45 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:17:45 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-11] mopidy_tidal.utils NotImplementedError:
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-11] mopidy_tidal.utils run(<TidalSearchThread(Thread-11, started 1836033120)>, )
Dec 11 15:17:45 rpimedia mopidy[5420]: Exception in thread Thread-11:
Dec 11 15:17:45 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:17:45 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:17:45 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:17:45 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Dec 11 15:17:45 rpimedia mopidy[5420]:     self.run()
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:17:45 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 65, in run
Dec 11 15:17:45 rpimedia mopidy[5420]:     artists = self.session.search("artist", self.keyword).artists
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:17:45 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:17:45 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:17:45 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:17:45 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:17:45 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-12] mopidy_tidal.utils Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:17:45 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:17:45 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:17:45 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:17:45 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 68, in run
Dec 11 15:17:45 rpimedia mopidy[5420]:     albums = self.session.search("album", self.keyword).albums
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:17:45 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:17:45 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:17:45 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:17:45 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:17:45 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-12] mopidy_tidal.utils NotImplementedError:
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-13] mopidy_tidal.utils Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:17:45 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:17:45 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:17:45 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:17:45 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 71, in run
Dec 11 15:17:45 rpimedia mopidy[5420]:     tracks = self.session.search("track", self.keyword).tracks
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:17:45 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:17:45 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:17:45 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:17:45 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:17:45 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:17:45 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:17:45 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-12] mopidy_tidal.utils run(<TidalSearchThread(Thread-12, started 1827640416)>, )
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-13] mopidy_tidal.utils NotImplementedError:
Dec 11 15:17:45 rpimedia mopidy[5420]: ERROR    [Thread-13] mopidy_tidal.utils run(<TidalSearchThread(Thread-13, started 1819247712)>, )
Dec 11 15:19:39 rpimedia mopidy[5420]: Exception in thread Thread-12:
Dec 11 15:19:39 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:19:39 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:19:39 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:19:39 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:19:39 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Dec 11 15:19:39 rpimedia mopidy[5420]:     self.run()
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:19:39 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 68, in run
Dec 11 15:19:39 rpimedia mopidy[5420]:     albums = self.session.search("album", self.keyword).albums
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:19:39 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:19:39 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:19:39 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:19:39 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:19:39 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:19:39 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:19:39 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:19:39 rpimedia mopidy[5420]: Exception in thread Thread-13:
Dec 11 15:19:39 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 94, in auth_info
Dec 11 15:19:39 rpimedia mopidy[5420]:     with open(self._config.auth_json_file, 'r') as f:
Dec 11 15:19:39 rpimedia mopidy[5420]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'
Dec 11 15:19:39 rpimedia mopidy[5420]: During handling of the above exception, another exception occurred:
Dec 11 15:19:39 rpimedia mopidy[5420]: Traceback (most recent call last):
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Dec 11 15:19:39 rpimedia mopidy[5420]:     self.run()
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/utils.py", line 38, in wrapper
Dec 11 15:19:39 rpimedia mopidy[5420]:     return func(*args, **kwargs)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.3.0-py3.7.egg/mopidy_tidal/search.py", line 71, in run
Dec 11 15:19:39 rpimedia mopidy[5420]:     tracks = self.session.search("track", self.keyword).tracks
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 388, in search
Dec 11 15:19:39 rpimedia mopidy[5420]:     result = self._map_request(url, params, ret=ret_type)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 324, in _map_request
Dec 11 15:19:39 rpimedia mopidy[5420]:     json_obj = self.request('GET', url, params)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 192, in request
Dec 11 15:19:39 rpimedia mopidy[5420]:     resp = self._request(*args, **kwargs)
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 204, in _request
Dec 11 15:19:39 rpimedia mopidy[5420]:     'countryCode': self.country_code,
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 119, in country_code
Dec 11 15:19:39 rpimedia mopidy[5420]:     return self.auth_info["user"]["countryCode"]
Dec 11 15:19:39 rpimedia mopidy[5420]:   File "/usr/local/lib/python3.7/dist-packages/tidaloauth4mopidy-0.2.0-py3.7.egg/tidaloauth4mopidy/__init__.py", line 97, in auth_info
Dec 11 15:19:39 rpimedia mopidy[5420]:     raise NotImplementedError
Dec 11 15:19:39 rpimedia mopidy[5420]: NotImplementedError
Dec 11 15:19:39 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.lru_cache Search cache hit
Dec 11 15:20:41 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.lru_cache Search cache hit
Dec 11 15:22:09 rpimedia mopidy[5420]: INFO     [TidalBackend-3] mopidy_tidal.lru_cache Search cache hit
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands GLib mainloop got SIGTERM. Exiting...
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Stopping Mopidy frontends
Dec 11 15:33:30 rpimedia systemd[1]: Stopping Mopidy music server...
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Stopping Mopidy core
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Stopping Mopidy backends
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Stopping Mopidy audio
Dec 11 15:33:30 rpimedia mopidy[5420]: INFO     [MainThread] mopidy.commands Stopping Mopidy mixer
Dec 11 15:33:30 rpimedia systemd[1]: mopidy.service: Succeeded.
Dec 11 15:33:30 rpimedia systemd[1]: Stopped Mopidy music server.
Dec 11 15:33:30 rpimedia systemd[1]: Starting Mopidy music server...
Dec 11 15:33:30 rpimedia systemd[1]: Started Mopidy music server.
Dec 11 15:33:33 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Dec 11 15:33:33 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Dec 11 15:33:33 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Dec 11 15:33:33 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Dec 11 15:33:33 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.config Loading config from command line options
Dec 11 15:33:34 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.__main__ Enabled extensions: mobile, file, mpd, http, musicbox_webclient, stream, tidal, softwaremixer, m3u, alsamixer
Dec 11 15:33:34 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: TidalBackend, FileBackend, M3UBackend, StreamBackend
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [TidalBackend-3] mopidy_tidal.backend Connecting to TIDAL.. Quality = HIGH
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink device=hw:1,0"
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:0.0.0.0]:6600
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [HttpFrontend-10] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Dec 11 15:33:35 rpimedia mopidy[7617]: INFO     [MainThread] mopidy.commands Starting GLib mainloop

FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/tidaloa.cred'

Maybe you can elaborate on how to setup the token, tidaloa.cred file?

**Comment by tehkillerbee** [comment]
I see you have provided more details on your own fork of this repository. I will gladly merge your code, if it works as it should. I see no need to have multiple Mopidy-Tidal plugins. Naturally, I can add you as a contributor as well, if you are planning to continue maintaining the plugin.

**Comment by quodrum-glas** [comment]
I have just tested now the OAuth method and it did work. I used the token from an Android Tidal app v2.33.6
Tokens are important in this, as the legacy tokens do not work for OAuth. I still had to use Python2 version as it proved not to be straightforward to update to Mopidy 3 on my system and stopped investing more time for a while in all this.

So I don't know how to debug the issue with the Tidal server.
I'm also due to visit again the update to Mopidy 3.
I will come back after testing same code, the dev branch - Python3.

**Comment by tehkillerbee** [comment]
@quodrum-glas I could not get it working at the time, but I was using Python 3 for all tests - maybe that is why. 

I also had issues upgrading mopidy from python 2 to 3 in the past. I ended up wiping the Raspberry Pi and starting over ;)

In any case, you have added some very valuable additions to the plugin. While I would like to wait with OAuth authentification until this is supported by the python-tidal plugin (I am not a maintainer of this plugin and I can imagine it will require a lot of work maintaining), your caching improvements would be very nice to merge into this project. I will look into this ASAP.

**Comment by tehkillerbee** [comment]
Closing, as tidalapi has now added OAuth login support. However, there are still useful additions (namely the image caching) that would be nice to add to the mopidy-tidal.

**Pull request closed without merging**
